application: better-ning-feeds
version: 1
runtime: python27
threadsafe: true
api_version: 1

builtins:
- appstats: on
- deferred: on

libraries:
- name: jinja2
  version: 2.6
- name: django
  version: 1.2

handlers:
- url: /tasks/improve_feeds
  script: better_ning_feeds.application
  login: admin
- url: /admin
  script: better_ning_feeds.application
  login: admin
- url: /.*
  script: better_ning_feeds.application
