application: better-ning-feeds
version: 1
runtime: python27
threadsafe: false
api_version: 1

builtins:
- appstats: on

handlers:
- url: /tasks/improve_feeds
  script: better_ning_feeds.application
  login: admin
- url: /.*
  script: better_ning_feeds.application
